### ISSUE TITLE
Systemd-efistub: configuration files generated for other distribution

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#163]
Major:
When other kernels are present on the /boot partition, m-a generates config files for them even if they are not manjaro related.

Steps to reproduce:
Mount /boot on an existing ESP partition with existing kernels

content of /boot & /boot/loader/entries/
➜  boot la
drwxr-xr-x  5 root root     4096 Jan  1  1970 .
-rwxr-xr-x  1 root root  4970256 Apr 27 14:16 vmlinuz-linux
-rwxr-xr-x  1 root root   987648 May 13 11:38 intel-ucode.img
-rwxr-xr-x  1 root root  4912928 May 14 15:33 vmlinuz-4.9-x86_64
-rwxr-xr-x  1 root root       21 May 14 15:33 linux49-x86_64.kver
-rwxr-xr-x  1 root root  5412624 May 14 19:36 vmlinuz-4.10.16_1
-rwxr-xr-x  1 root root  5826571 May 18 12:55 initramfs-linux.img
-rwxr-xr-x  1 root root 22820229 May 18 12:55 initramfs-linux-fallback.img
-rwxr-xr-x  1 root root 34776158 May 19 00:26 initramfs-4.10.16_1.img
-rwxr-xr-x  1 root root  5826730 May 19 11:36 initramfs-4.9-x86_64.img
-rwxr-xr-x  1 root root 22173854 May 19 11:36 initramfs-4.9-x86_64-fallback.img
drwxr-xr-x 18 root root     4096 May 19 12:11 ..
➜  boot la loader/entries 
-rwxr-xr-x 1 root root  149 May 18 12:55 base-fallback.conf
-rwxr-xr-x 1 root root  129 May 18 12:55 base.conf
drwxr-xr-x 3 root root 4096 May 18 21:58 ..
-rwxr-xr-x 1 root root  136 May 19 00:34 other.conf
-rwxr-xr-x 1 root root  161 May 19 11:43 manjaro-linux.conf
-rwxr-xr-x 1 root root  176 May 19 11:43 manjaro-4.9-x86_64.conf
-rwxr-xr-x 1 root root  173 May 19 11:43 manjaro-4.10.16_1.conf
drwxr-xr-x 2 root root 4096 May 19 11:43 .

Strange fully the fallback images are not used so it is based on the vmlinuz only?

**Comment by Chrysostomus** [comment]
Fixed with commit fc45637 (latest commit). 

We could maybe add the fallback entries too. Previously fallback entries were filtered out because they produced unbootable entries.

**Comment by Onfroygmx** [comment]
Has this been included in latest build.
Have tested with : : manjaro-architect 0.8.11-2 ::
And still have the conf files generated for the vmlinuz-linuz.
/boot/loader/entries/manjaro-linux.conf

title	Manjaro Linux linux
linux	/vmlinuz-linux
initrd	/intel-ucode.img
initrd	/initramfs-linux.img
options	root=/dev/mapper/vgcrypt-root  cryptdevice=UUID=4d29012c-150b-4956-8afe-5ec35eed23a9:vgcrypt-root rw

**Comment by oberon-manjaro** [comment]
No it's not included in the stable release, yet. I will make a fresh package **manjaro-architect-dev** for unstable branch now.
Let me know when a new stable package makes sense, @Chrysostomus or just create the tag when it  makes sense and I'll be notified anyway.

**Comment by oberon-manjaro** [comment]
**manjaro-architect-dev-0.8.11.r3.g8a0f62e** is on unstable branch now
